import test from "node:test";
import assert from "node:assert/strict";
import { presentJurisdictionSourcePolicyExceptionCard as present } from "./xvi-jurisdiction-source-policy-exception-card";

type R="LICENSE_MISSING"|"PROVENANCE_INVALID"|"RESTRICTED_PERSONAL_DATA"|"RESOURCE_CEILING";
type M="ONLINE_GOVERNED"|"OFFLINE_GOVERNED"|"LOCAL_ONLY";
const disp=(r:R)=>r==="RESOURCE_CEILING"?"DEFERRED":r==="PROVENANCE_INVALID"?"QUARANTINED":r==="RESTRICTED_PERSONAL_DATA"?"REJECTED":"NEEDS_REVIEW";
function item(r:R,i=1,x:Record<string,unknown>={}){const d=disp(r);return{exceptionId:`source-policy-exception:${i}`,tenantId:"tenant:a",jurisdictionId:"jurisdiction:za",sourceId:`source:${i}`,dedupKey:i.toString(16).padStart(64,"0"),reason:r,disposition:d,evidenceHash:(i+10).toString(16).padStart(64,"0"),evidenceBindingHash:(i+20).toString(16).padStart(64,"0"),replayKey:(i+30).toString(16).padStart(64,"0"),exceptionDigest:(i+40).toString(16).padStart(64,"0"),attemptCount:0,maxRetries:3,canRetry:r==="RESOURCE_CEILING",requiresHumanReview:d!=="DEFERRED",firstObservedAt:"2026-10-02T08:50:00.000Z",lastObservedAt:"2026-10-02T08:55:00.000Z",safeReadOnly:true,canFetchExternalData:false,canFeedCountryCell:false,canFeedCore:false,executionAuthority:false,mutationAuthority:false,productionAuthority:false,...x};}
function batch(xs:any[],mode:M="ONLINE_GOVERNED",x:Record<string,unknown>={}){const n=(d:string)=>xs.filter(v=>v.disposition===d).length;return{schemaVersion:"xvi-jurisdiction-source-policy-exception-v1",batchId:"source-policy-exception-batch:a",scheduleId:"jurisdiction-schedule:a",globalFeedPlanId:"global-feed:a",tenantId:"tenant:a",jurisdictionId:"jurisdiction:za",runMode:mode,observedAt:"2026-10-02T09:00:00.000Z",exceptionCount:xs.length,deferredCount:n("DEFERRED"),needsReviewCount:n("NEEDS_REVIEW"),quarantinedCount:n("QUARANTINED"),rejectedCount:n("REJECTED"),exceptions:xs,replayScope:"BATCH_ONLY",requiresDurableReplayLedger:true,zeroSecretContext:true,safeReadOnly:true,canFetchExternalData:false,canFeedCountryCell:false,canFeedCore:false,executionAuthority:false,mutationAuthority:false,productionAuthority:false,...x};}
const input=(receipt:any)=>({receipt,safeReadOnly:true,requiresUserGesture:true,canAutoNavigate:false,canFetchExternalData:false,canFeedCore:false,canMutate:false,canClaimIngestion:false});

test("routes deferred to Universe and review states to Needs You",()=>{assert.equal(present(input(batch([item("RESOURCE_CEILING")]))).lane,"UNIVERSE");assert.equal(present(input(batch([item("LICENSE_MISSING")]))).lane,"NEEDS_YOU");assert.equal(present(input(batch([item("PROVENANCE_INVALID")]))).reviewState,"QUARANTINED");assert.equal(present(input(batch([item("RESTRICTED_PERSONAL_DATA")]))).reviewState,"REJECTED");});
test("all governed modes preserve labels and zero authority",()=>{for(const [m,l] of [["ONLINE_GOVERNED","Online governed"],["OFFLINE_GOVERNED","Offline governed"],["LOCAL_ONLY","Local only"]] as const){const c=present(input(batch([item("LICENSE_MISSING")],m)));assert.equal(c.modeLabel,l);assert.equal(c.canFetchExternalData,false);assert.equal(c.canFeedCore,false);assert.equal(c.executionAuthority,false);}});
test("summary forgery fails closed",()=>{assert.throws(()=>present(input(batch([item("LICENSE_MISSING")],"ONLINE_GOVERNED",{needsReviewCount:0}))),/SUMMARY_COUNT_MISMATCH/);});
test("duplicate replay keys fail closed",()=>{const a=item("LICENSE_MISSING",1),b=item("LICENSE_MISSING",2,{replayKey:a.replayKey});assert.throws(()=>present(input(batch([a,b]))),/REPLAY_DUPLICATE/);});
test("future evidence and malformed hashes fail closed",()=>{assert.throws(()=>present(input(batch([item("LICENSE_MISSING",1,{lastObservedAt:"2026-10-02T09:01:00.000Z"})]))),/FROM_FUTURE/);assert.throws(()=>present(input(batch([item("LICENSE_MISSING",1,{evidenceHash:"bad"})]))),/EVIDENCE_INVALID/);});
test("hidden fields fail exact schema",()=>{assert.throws(()=>present({...input(batch([item("LICENSE_MISSING")])),hidden:true}),/SCHEMA_MISMATCH/);});
