export type Mode='ONLINE_GOVERNED'|'OFFLINE_GOVERNED'|'LOCAL_ONLY';
export type State='READY_TO_REVIEW'|'SUBMITTING_INTENT'|'AWAITING_AUTHENTICATED_RECEIPT'|'REVIEW_READY_WITH_RECEIPT'|'STALE_RECHECK_REQUIRED'|'REVIEW_REJECTED'|'SAFE_READ_ONLY_RECOVERY'|'DEFERRED';
export type Event=
 |{type:'SUBMIT';mode:Mode}|{type:'INTENT_ACCEPTED';mode:Mode}
 |{type:'RECEIPT_VERIFIED';mode:Mode;receiptDigest:string;expiresAt:string}
 |{type:'STALE';mode:Mode}|{type:'REJECT';mode:Mode}|{type:'SAFE_RECOVERY';mode:Mode}
 |{type:'RETRY';mode:Mode}|{type:'DEFER';mode:Mode};
export type ReviewLifecycle=Readonly<{state:State;mode:Mode;receiptDigest:string|null;receiptExpiresAt:string|null;safeReadOnly:boolean;adoptionConfirmed:false;executionAuthority:false;mutationAuthority:false;productionAuthority:false}>;
export type Presentation=Readonly<{title:string;body:string;primaryAction:string|null;secondaryAction:string|null;statusLabel:string;accessibilityLabel:string;canClaimSuccess:false}>;
const MODES=new Set<Mode>(['ONLINE_GOVERNED','OFFLINE_GOVERNED','LOCAL_ONLY']); const HEX=/^[a-f0-9]{64}$/;
export function createReviewLifecycle(mode:Mode):ReviewLifecycle{modeOk(mode);return freeze('READY_TO_REVIEW',mode,null,null,false)}
export function transitionReviewLifecycle(s:ReviewLifecycle,e:Event,now:string):ReviewLifecycle{stateOk(s);eventOk(e);iso(now,'NOW_INVALID');if(e.mode!==s.mode&&e.type!=='STALE')return freeze('SAFE_READ_ONLY_RECOVERY',e.mode,null,null,true);switch(e.type){case'SUBMIT':return ['READY_TO_REVIEW','STALE_RECHECK_REQUIRED','REVIEW_REJECTED','DEFERRED'].includes(s.state)?freeze('SUBMITTING_INTENT',e.mode,null,null,false):s;case'INTENT_ACCEPTED':return s.state==='SUBMITTING_INTENT'?freeze('AWAITING_AUTHENTICATED_RECEIPT',e.mode,null,null,false):s;case'RECEIPT_VERIFIED':if(s.state!=='AWAITING_AUTHENTICATED_RECEIPT')return s;return Date.parse(e.expiresAt)<=Date.parse(now)?freeze('STALE_RECHECK_REQUIRED',e.mode,null,null,true):freeze('REVIEW_READY_WITH_RECEIPT',e.mode,e.receiptDigest,e.expiresAt,true);case'STALE':return freeze('STALE_RECHECK_REQUIRED',e.mode,null,null,true);case'REJECT':return freeze('REVIEW_REJECTED',e.mode,null,null,true);case'SAFE_RECOVERY':return freeze('SAFE_READ_ONLY_RECOVERY',e.mode,null,null,true);case'RETRY':return ['STALE_RECHECK_REQUIRED','REVIEW_REJECTED','SAFE_READ_ONLY_RECOVERY','DEFERRED'].includes(s.state)?freeze('READY_TO_REVIEW',e.mode,null,null,false):s;case'DEFER':return freeze('DEFERRED',e.mode,null,null,true)}}
export function presentReviewLifecycle(s:ReviewLifecycle):Presentation{stateOk(s);const m=s.mode.replaceAll('_',' ');const x={canClaimSuccess:false as const};switch(s.state){case'READY_TO_REVIEW':return Object.freeze({...x,title:'Review trust protection update',body:`Review the latest governed protection state in ${m}. Nothing changes automatically.`,primaryAction:'Continue review',secondaryAction:'Not now',statusLabel:'Ready for review',accessibilityLabel:`Trust protection update. ${m}. Nothing changes automatically.`});case'SUBMITTING_INTENT':return Object.freeze({...x,title:'Sending review intent',body:'Sending only your intent to review. No update has been applied.',primaryAction:null,secondaryAction:null,statusLabel:'Submitting intent',accessibilityLabel:'Submitting review intent. No update has been applied.'});case'AWAITING_AUTHENTICATED_RECEIPT':return Object.freeze({...x,title:'Verifying review context',body:'Waiting for a fresh authenticated review receipt. No update has been applied.',primaryAction:null,secondaryAction:'Not now',statusLabel:'Awaiting verification',accessibilityLabel:'Awaiting authenticated review receipt. No update has been applied.'});case'REVIEW_READY_WITH_RECEIPT':return Object.freeze({...x,title:'Review context verified',body:'The review context is verified and read-only. This does not mean a trust update was adopted or executed.',primaryAction:'Open review',secondaryAction:'Not now',statusLabel:'Verified for review',accessibilityLabel:'Review context verified. No trust update has been adopted or executed.'});case'STALE_RECHECK_REQUIRED':return Object.freeze({...x,title:'Fresh check required',body:'Security state changed. Recheck before continuing.',primaryAction:'Recheck safely',secondaryAction:'Not now',statusLabel:'Stale state',accessibilityLabel:'Fresh security check required.'});case'REVIEW_REJECTED':return Object.freeze({...x,title:'Review cannot continue',body:'Security policy rejected the review. Nothing was changed.',primaryAction:'Try again',secondaryAction:'Close',statusLabel:'Review rejected',accessibilityLabel:'Review rejected. Nothing was changed.'});case'SAFE_READ_ONLY_RECOVERY':return Object.freeze({...x,title:'Safe read-only recovery',body:'Write-capable review progression is stopped until recovery state is trustworthy again.',primaryAction:'Recheck safely',secondaryAction:'Close',statusLabel:'Read-only recovery',accessibilityLabel:'Safe read-only recovery. No write-capable action is available.'});case'DEFERRED':return Object.freeze({...x,title:'Review saved for later',body:'The review remains pending. No update was applied.',primaryAction:'Review now',secondaryAction:null,statusLabel:'Deferred',accessibilityLabel:'Review deferred. No update was applied.'})}}
function eventOk(e:Event){if(e===null||typeof e!=='object'||Object.getPrototypeOf(e)!==Object.prototype)throw Error('EVENT_PLAIN_OBJECT_REQUIRED');if(Object.getOwnPropertySymbols(e).length)throw Error('EVENT_SYMBOLS_FORBIDDEN');for(const k of Object.keys(e)){const d=Object.getOwnPropertyDescriptor(e,k);if(!d||d.get||d.set)throw Error('EVENT_ACCESSOR_FORBIDDEN')}modeOk(e.mode);if(e.type==='RECEIPT_VERIFIED'){if(!HEX.test(e.receiptDigest))throw Error('RECEIPT_DIGEST_INVALID');iso(e.expiresAt,'RECEIPT_EXPIRY_INVALID')}}
function stateOk(s:ReviewLifecycle){modeOk(s.mode);if(s.adoptionConfirmed!==false||s.executionAuthority!==false||s.mutationAuthority!==false||s.productionAuthority!==false)throw Error('AUTHORITY_CLAIM_FORBIDDEN');if(s.receiptDigest!==null&&!HEX.test(s.receiptDigest))throw Error('RECEIPT_DIGEST_INVALID')}
function modeOk(m:string):asserts m is Mode{if(!MODES.has(m as Mode))throw Error('MODE_INVALID')}function iso(v:string,c:string){if(typeof v!=='string'||!v.includes('T')||Number.isNaN(Date.parse(v)))throw Error(c)}function freeze(state:State,mode:Mode,receiptDigest:string|null,receiptExpiresAt:string|null,safeReadOnly:boolean):ReviewLifecycle{return Object.freeze({state,mode,receiptDigest,receiptExpiresAt,safeReadOnly,adoptionConfirmed:false,executionAuthority:false,mutationAuthority:false,productionAuthority:false})}