import test from 'node:test'; import assert from 'node:assert/strict';
import {createReviewLifecycle as create,transitionReviewLifecycle as step,presentReviewLifecycle as present} from './xvi-needs-you-review-lifecycle';
const NOW='2026-10-01T00:15:00-05:00', D='a'.repeat(64);
test('starts zero-authority',()=>{const s=create('LOCAL_ONLY');assert.equal(s.state,'READY_TO_REVIEW');assert.equal(s.adoptionConfirmed,false);assert.equal(s.productionAuthority,false)});
test('receipt means ready-to-review, not adopted',()=>{let s=create('ONLINE_GOVERNED');s=step(s,{type:'SUBMIT',mode:s.mode},NOW);s=step(s,{type:'INTENT_ACCEPTED',mode:s.mode},NOW);s=step(s,{type:'RECEIPT_VERIFIED',mode:s.mode,receiptDigest:D,expiresAt:'2026-10-01T00:16:00-05:00'},NOW);assert.equal(s.state,'REVIEW_READY_WITH_RECEIPT');assert.equal(s.adoptionConfirmed,false);assert.equal(present(s).canClaimSuccess,false)});
test('expired receipt becomes stale',()=>{let s=create('ONLINE_GOVERNED');s=step(s,{type:'SUBMIT',mode:s.mode},NOW);s=step(s,{type:'INTENT_ACCEPTED',mode:s.mode},NOW);s=step(s,{type:'RECEIPT_VERIFIED',mode:s.mode,receiptDigest:D,expiresAt:'2026-10-01T00:14:59-05:00'},NOW);assert.equal(s.state,'STALE_RECHECK_REQUIRED');assert.equal(s.receiptDigest,null)});
test('mode drift fails read-only',()=>{const s=step(create('ONLINE_GOVERNED'),{type:'SUBMIT',mode:'OFFLINE_GOVERNED'},NOW);assert.equal(s.state,'SAFE_READ_ONLY_RECOVERY');assert.equal(s.safeReadOnly,true)});
test('recovery can retry',()=>{let s=step(create('LOCAL_ONLY'),{type:'SAFE_RECOVERY',mode:'LOCAL_ONLY'},NOW);s=step(s,{type:'RETRY',mode:'LOCAL_ONLY'},NOW);assert.equal(s.state,'READY_TO_REVIEW')});
test('bad digest rejected',()=>{let s=create('ONLINE_GOVERNED');s=step(s,{type:'SUBMIT',mode:s.mode},NOW);s=step(s,{type:'INTENT_ACCEPTED',mode:s.mode},NOW);assert.throws(()=>step(s,{type:'RECEIPT_VERIFIED',mode:s.mode,receiptDigest:'bad',expiresAt:'2026-10-01T00:16:00-05:00'},NOW),/RECEIPT_DIGEST_INVALID/)});
test('symbol event rejected',()=>{const e:any={type:'DEFER',mode:'LOCAL_ONLY'};e[Symbol('x')]=1;assert.throws(()=>step(create('LOCAL_ONLY'),e,NOW),/EVENT_SYMBOLS_FORBIDDEN/)});
test('accessor event rejected without getter execution',()=>{let hits=0;const e:any={type:'DEFER',mode:'LOCAL_ONLY'};Object.defineProperty(e,'x',{enumerable:true,get(){hits++;return 1}});assert.throws(()=>step(create('LOCAL_ONLY'),e,NOW),/EVENT_ACCESSOR_FORBIDDEN/);assert.equal(hits,0)});
test('exotic prototype event rejected',()=>{const e:any=Object.create({});e.type='DEFER';e.mode='LOCAL_ONLY';assert.throws(()=>step(create('LOCAL_ONLY'),e,NOW),/EVENT_PLAIN_OBJECT_REQUIRED/)});
test('copy never claims success',()=>{const p=present(create('OFFLINE_GOVERNED'));assert.equal(p.canClaimSuccess,false);assert.match(p.body,/Nothing changes automatically/)})