/**
 * Scorecard generator.
 *
 * The rules this renders by, and the reason it exists:
 *   - TBD is not PASS. A threshold with no measured value is UNVERIFIED.
 *   - UNCONFIGURED is not PASS. A subsystem nothing is configured for is
 *     reported as unconfigured, not as working.
 *   - DOCUMENTED is not IMPLEMENTED, and IMPLEMENTED is not VERIFIED. Every row
 *     here is the output of code that ran in the recorded run.
 */
import { execFileSync } from 'node:child_process';
import type { AcceptanceResult, Threshold, ThresholdStatus } from './harness';

export type RunMetadata = {
  ranAt: string;
  commit: string;
  branch: string;
  nodeVersion: string;
  platform: string;
  cpuModel: string;
  cpuCount: number;
  totalMemoryMb: number;
  durationMs: number;
};

export type Scorecard = {
  metadata: RunMetadata;
  results: AcceptanceResult[];
  counts: Record<AcceptanceResult['status'], number>;
  thresholdCounts: Record<ThresholdStatus, number>;
  blockers: string[];
  openItems: { ac: string; threshold: string; status: ThresholdStatus; note: string }[];
  gate: 'GO' | 'NO-GO';
};

export function gitValue(args: string[], fallback: string): string {
  try {
    return execFileSync('git', args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim() || fallback;
  } catch {
    return fallback;
  }
}

export function buildScorecard(results: AcceptanceResult[], metadata: RunMetadata): Scorecard {
  const counts: Record<AcceptanceResult['status'], number> = { PASS: 0, FAIL: 0, PARTIAL: 0, UNVERIFIED: 0 };
  const thresholdCounts: Record<ThresholdStatus, number> = { PASS: 0, FAIL: 0, UNVERIFIED: 0, UNCONFIGURED: 0 };
  const blockers: string[] = [];
  const openItems: Scorecard['openItems'] = [];

  for (const result of results) {
    counts[result.status] += 1;
    blockers.push(...result.blockers);
    for (const threshold of result.thresholds) {
      thresholdCounts[threshold.status] += 1;
      if (threshold.status === 'UNVERIFIED' || threshold.status === 'UNCONFIGURED') {
        openItems.push({
          ac: result.id,
          threshold: threshold.label,
          status: threshold.status,
          note: threshold.note ?? '',
        });
      }
    }
  }

  // The gate opens only when every criterion passed outright. A partial result
  // means something in it was not verified, and that is not a pass.
  const gate: Scorecard['gate'] = counts.PASS === results.length && blockers.length === 0 ? 'GO' : 'NO-GO';

  return { metadata, results, counts, thresholdCounts, blockers, openItems, gate };
}

const STATUS_MARK: Record<ThresholdStatus, string> = {
  PASS: 'PASS',
  FAIL: 'FAIL',
  UNVERIFIED: 'UNVERIFIED',
  UNCONFIGURED: 'UNCONFIGURED',
};

function thresholdRow(threshold: Threshold): string {
  const blocker = threshold.blocker ? ' (gate blocker)' : '';
  const note = threshold.note ? ` ${threshold.note}` : '';
  return `| ${threshold.label}${blocker} | ${threshold.target} | ${threshold.measured} | ${STATUS_MARK[threshold.status]} |${note} |`;
}

export function renderScorecard(scorecard: Scorecard): string {
  const { metadata, results, counts, thresholdCounts } = scorecard;
  const lines: string[] = [];

  lines.push('# XIV 62D — Distributed Device, Chip & Edge Runtime: Readiness Scorecard');
  lines.push('');
  lines.push(
    'Generated by `npm run acceptance` in `services/runtime`. Every row below is the output of code that ran in the recorded run; nothing here is asserted from a design document.',
  );
  lines.push('');
  lines.push(`- Run at: ${metadata.ranAt}`);
  lines.push(`- Commit: \`${metadata.commit}\` on \`${metadata.branch}\``);
  lines.push(`- Runtime: Node ${metadata.nodeVersion} on ${metadata.platform}`);
  lines.push(`- Host: ${metadata.cpuCount} × ${metadata.cpuModel}, ${metadata.totalMemoryMb} MB RAM`);
  lines.push(`- Suite duration: ${(metadata.durationMs / 1000).toFixed(1)}s`);
  lines.push('');
  lines.push(`## Canary gate: ${scorecard.gate}`);
  lines.push('');
  if (scorecard.gate === 'GO') {
    lines.push('Every acceptance criterion passed with measured evidence and no gate blocker failed.');
  } else {
    lines.push(
      'The gate is closed. A criterion is only a PASS when every one of its thresholds was measured and met; anything unverified or unconfigured holds the gate closed.',
    );
    if (scorecard.blockers.length) {
      lines.push('');
      lines.push('Failed gate blockers:');
      lines.push('');
      for (const blocker of scorecard.blockers) lines.push(`- \`${blocker}\``);
    }
  }
  lines.push('');
  lines.push(
    `Criteria: ${counts.PASS} pass, ${counts.FAIL} fail, ${counts.PARTIAL} partial, ${counts.UNVERIFIED} unverified of ${results.length}.`,
  );
  lines.push(
    `Thresholds: ${thresholdCounts.PASS} pass, ${thresholdCounts.FAIL} fail, ${thresholdCounts.UNVERIFIED} unverified, ${thresholdCounts.UNCONFIGURED} unconfigured.`,
  );
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push('| AC | Criterion | Status | Thresholds met | Failed blockers |');
  lines.push('| --- | --- | --- | --- | --- |');
  for (const result of results) {
    const met = result.thresholds.filter((threshold) => threshold.status === 'PASS').length;
    lines.push(
      `| ${result.id} | ${result.title} | ${result.status} | ${met}/${result.thresholds.length} | ${result.blockers.length} |`,
    );
  }
  lines.push('');

  if (scorecard.openItems.length) {
    lines.push('## Not verified in this run');
    lines.push('');
    lines.push('These thresholds were not measured. They are not passes, and each one states why.');
    lines.push('');
    lines.push('| AC | Threshold | Status | Reason |');
    lines.push('| --- | --- | --- | --- |');
    for (const item of scorecard.openItems) {
      lines.push(`| ${item.ac} | ${item.threshold} | ${item.status} | ${item.note || 'no reason recorded'} |`);
    }
    lines.push('');
  }

  lines.push('## Measured evidence by criterion');
  lines.push('');
  for (const result of results) {
    lines.push(`### ${result.id} — ${result.title} — ${result.status}`);
    lines.push('');
    lines.push('| Threshold | Target | Measured | Status | Note |');
    lines.push('| --- | --- | --- | --- | --- |');
    for (const threshold of result.thresholds) lines.push(thresholdRow(threshold));
    lines.push('');
    const evidenceNote = result.evidence.note;
    if (typeof evidenceNote === 'string') {
      lines.push(`Scope of this evidence: ${evidenceNote}`);
      lines.push('');
    }
    lines.push('<details><summary>Evidence</summary>');
    lines.push('');
    lines.push('```json');
    lines.push(JSON.stringify(result.evidence, replacer, 2));
    lines.push('```');
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  lines.push('## How to reproduce');
  lines.push('');
  lines.push('```bash');
  lines.push('cd services/runtime');
  lines.push('npm install');
  lines.push('npm run typecheck');
  lines.push('npm test');
  lines.push('npm run acceptance   # writes docs/62d/SCORECARD.md and acceptance-evidence.json');
  lines.push('```');
  lines.push('');
  lines.push(
    'The database row level security evidence needs a local PostgreSQL server (`npm run verify:rls` runs it standalone). Without one, AC-03 reports its database layer as UNVERIFIED rather than assuming the policies hold.',
  );
  lines.push('');

  return `${lines.join('\n')}\n`;
}

/** Keeps very large evidence arrays readable without hiding their size. */
function replacer(_key: string, value: unknown): unknown {
  if (Array.isArray(value) && value.length > 40) {
    return [...value.slice(0, 20), `… ${value.length - 20} more entries omitted from this rendering`];
  }
  return value;
}

export function renderConsoleSummary(scorecard: Scorecard): string {
  const lines: string[] = [];
  for (const result of scorecard.results) {
    const met = result.thresholds.filter((threshold) => threshold.status === 'PASS').length;
    lines.push(`${result.id.padEnd(6)} ${result.status.padEnd(10)} ${String(met).padStart(2)}/${result.thresholds.length} ${result.title}`);
    for (const threshold of result.thresholds) {
      if (threshold.status === 'PASS') continue;
      lines.push(`         ${threshold.status.padEnd(12)} ${threshold.label}: measured ${threshold.measured} against ${threshold.target}`);
    }
  }
  lines.push('');
  lines.push(`gate: ${scorecard.gate}`);
  return lines.join('\n');
}
