// Side-effect CSS imports (theme.ts imports '@/global.css', handled by Metro)
// have no type declarations in this project until expo-env.d.ts / .expo types
// are generated by a dev server. This ambient declaration keeps `tsc --noEmit`
// passing in clean checkouts; it declares no runtime API.
declare module '*.css';
