import type { EvidenceCategory, GateDefinition, GateId } from './types';

/**
 * The section 37 ownership matrix, as data rather than as a table in a
 * document. Owners and verifiers are role names: on a small team one person
 * may hold several, but the ledger still refuses to let a single actor be
 * implementation owner, independent verifier and human approver for the same
 * critical gate (section 36).
 */

const gate = (
  id: GateId,
  label: string,
  primaryOwner: string,
  requiredEvidence: GateDefinition['requiredEvidence'],
  requiredCategories: readonly EvidenceCategory[],
  independentVerifier: string,
  humanApproval: GateDefinition['humanApproval'],
  threshold: GateDefinition['threshold'],
  releaseCritical: boolean,
): GateDefinition => ({
  id,
  label,
  primaryOwner,
  requiredEvidence,
  requiredCategories,
  independentVerifier,
  humanApproval,
  threshold,
  releaseCritical,
});

const ALL_PASS = { kind: 'all_pass' } as const;

export const GATES: Readonly<Record<GateId, GateDefinition>> = Object.freeze({
  runtime_identity: gate(
    'runtime_identity',
    'Runtime identity',
    'Runtime Platform',
    'E3',
    ['negative', 'test_suite'],
    'Security',
    'exception_only',
    ALL_PASS,
    true,
  ),
  runtime_attestation: gate(
    'runtime_attestation',
    'Runtime attestation',
    'Security/Platform',
    'E3',
    ['runtime', 'test_suite'],
    'Security reviewer',
    'exception_only',
    ALL_PASS,
    true,
  ),
  rls: gate('rls', 'RLS', 'Database', 'E4', ['rls'], 'Security', 'exception_only', ALL_PASS, true),
  tenant_isolation: gate(
    'tenant_isolation',
    'Tenant isolation',
    'Database/Security',
    'E4',
    ['rls', 'negative'],
    'Independent security verifier',
    'exception_only',
    ALL_PASS,
    true,
  ),
  universe_isolation: gate(
    'universe_isolation',
    'Universe isolation',
    'Database/Security',
    'E4',
    ['rls', 'negative'],
    'Independent security verifier',
    'exception_only',
    ALL_PASS,
    true,
  ),
  workload_authorization: gate(
    'workload_authorization',
    'Workload authorization',
    'Runtime/Security',
    'E3',
    ['agent_security', 'negative'],
    'Security',
    'exception_only',
    ALL_PASS,
    true,
  ),
  compute_routing: gate(
    'compute_routing',
    'Compute routing',
    'Runtime Platform',
    'E3',
    ['test_suite'],
    'QA/Platform verifier',
    'none',
    { kind: 'ratio', minimum: 0.999 },
    false,
  ),
  intel_runtime: gate(
    'intel_runtime',
    'Intel runtime',
    'Runtime Platform',
    'E3',
    ['runtime'],
    'QA',
    'none',
    ALL_PASS,
    false,
  ),
  amd_runtime: gate('amd_runtime', 'AMD runtime', 'Runtime Platform', 'E3', ['runtime'], 'QA', 'none', ALL_PASS, false),
  nvidia_runtime: gate(
    'nvidia_runtime',
    'NVIDIA runtime',
    'Runtime/ML',
    'E3',
    ['runtime'],
    'QA/ML verifier',
    'none',
    ALL_PASS,
    false,
  ),
  ios: gate('ios', 'iOS', 'Mobile', 'E3', ['mobile'], 'QA/Security', 'required', ALL_PASS, false),
  android: gate('android', 'Android', 'Mobile', 'E3', ['mobile'], 'QA/Security', 'required', ALL_PASS, false),
  offline_mode: gate(
    'offline_mode',
    'Offline mode',
    'Runtime/Mobile',
    'E3',
    ['negative'],
    'Security',
    'exception_only',
    ALL_PASS,
    true,
  ),
  agent_runtime_assignment: gate(
    'agent_runtime_assignment',
    'Agent runtime assignment',
    'Agent Platform',
    'E3',
    ['agent_security'],
    'Security/QA',
    'none',
    ALL_PASS,
    false,
  ),
  resource_governor: gate(
    'resource_governor',
    'Resource governor',
    'Runtime Platform',
    'E3',
    ['negative', 'cost'],
    'SRE/QA',
    'none',
    ALL_PASS,
    true,
  ),
  kill_switch: gate('kill_switch', 'Kill switch', 'Runtime/SRE', 'E4', ['negative'], 'Security/SRE verifier', 'none', ALL_PASS, true),
  failure_recovery: gate(
    'failure_recovery',
    'Failure recovery',
    'SRE/Runtime',
    'E3',
    ['test_suite', 'negative'],
    'QA/SRE',
    'none',
    ALL_PASS,
    true,
  ),
  model_authorization: gate(
    'model_authorization',
    'Model authorization',
    'ML Platform',
    'E3',
    ['negative', 'model_evaluation'],
    'AI Evaluation/Security',
    'exception_only',
    ALL_PASS,
    true,
  ),
  agent_evaluation: gate(
    'agent_evaluation',
    'Agent evaluation',
    'AI Evaluation',
    'E3',
    ['agent_evaluation'],
    'Independent evaluator',
    'required',
    ALL_PASS,
    false,
  ),
  secret_scanning: gate(
    'secret_scanning',
    'Secret scanning',
    'Security',
    'E3',
    ['secret_scan'],
    'Security',
    'exception_only',
    { kind: 'max_findings', maximum: 0 },
    true,
  ),
  dependency_scanning: gate(
    'dependency_scanning',
    'Dependency scanning',
    'Security/Platform',
    'E3',
    ['dependency'],
    'Security',
    'exception_only',
    { kind: 'max_findings', maximum: 0 },
    true,
  ),
  provenance: gate('provenance', 'Provenance', 'Information Logistics', 'E4', ['lineage'], 'QA/Security', 'none', ALL_PASS, true),
  backup_restore: gate(
    'backup_restore',
    'Backup/restore',
    'Database/SRE',
    'E4',
    ['backup_restore'],
    'Independent SRE/DB reviewer',
    'required',
    ALL_PASS,
    true,
  ),
  rollback: gate('rollback', 'Rollback', 'Release/SRE', 'E4', ['rollback'], 'QA/SRE', 'required', ALL_PASS, true),
  cost_governance: gate(
    'cost_governance',
    'Cost governance',
    'FinOps/Platform',
    'E3',
    ['cost'],
    'Platform/Finance reviewer',
    'exception_only',
    ALL_PASS,
    false,
  ),
  canary_promotion: gate(
    'canary_promotion',
    'Canary promotion',
    'Release',
    'E4',
    ['test_suite'],
    'Security + QA',
    // Section 59: this one is reserved for the CEO or a separately authorized
    // human. Automation may prepare the package; it cannot sign it.
    'named_human',
    ALL_PASS,
    true,
  ),
});

export const GATE_IDS = Object.keys(GATES) as GateId[];

export function gateDefinition(id: GateId): GateDefinition {
  return GATES[id];
}

/** Section 39: the directory layout an evidence package is expected to take. */
export const EVIDENCE_PACKAGE_DIRECTORIES = [
  'unit',
  'integration',
  'security',
  'rls',
  'tenant-isolation',
  'api',
  'web',
  'mobile',
  'runtime',
  'agents',
  'models',
  'dependencies',
  'secrets',
  'performance',
  'cost',
  'provenance',
  'backup-restore',
  'rollback',
] as const;

export type EvidenceDirectory = (typeof EVIDENCE_PACKAGE_DIRECTORIES)[number];

const DIRECTORY_BY_GATE: Readonly<Record<GateId, EvidenceDirectory>> = Object.freeze({
  runtime_identity: 'runtime',
  runtime_attestation: 'runtime',
  rls: 'rls',
  tenant_isolation: 'tenant-isolation',
  universe_isolation: 'tenant-isolation',
  workload_authorization: 'security',
  compute_routing: 'runtime',
  intel_runtime: 'runtime',
  amd_runtime: 'runtime',
  nvidia_runtime: 'runtime',
  ios: 'mobile',
  android: 'mobile',
  offline_mode: 'security',
  agent_runtime_assignment: 'agents',
  resource_governor: 'runtime',
  kill_switch: 'security',
  failure_recovery: 'integration',
  model_authorization: 'models',
  agent_evaluation: 'agents',
  secret_scanning: 'secrets',
  dependency_scanning: 'dependencies',
  provenance: 'provenance',
  backup_restore: 'backup-restore',
  rollback: 'rollback',
  cost_governance: 'cost',
  canary_promotion: 'integration',
});

export function directoryForGate(id: GateId): EvidenceDirectory {
  return DIRECTORY_BY_GATE[id];
}

/** Gates that must appear in a candidate's evidence package (section 39). */
export const MANDATORY_GATES: readonly GateId[] = GATE_IDS.filter((id) => GATES[id].releaseCritical);
