import { refuse } from '../civilization/errors';
import type { EvidenceLevel, EvidenceRecord, EvidenceVerification } from './types';

// Section 35 — the five strength levels, implemented as a ladder that XIV
// climbs rather than a label an author picks.
//
// The whole point of the section is that saying "this is E4" is itself an E0
// claim. So the level a record is allowed to carry is derived from what the
// record demonstrably has: an artifact, an exact commit, a non-human executor, a
// way to reproduce it, an independent reviewer. A caller may state the level it
// expects, and if the evidence does not reach it the write is refused instead of
// being quietly downgraded — a caller that thinks it produced E3 and actually
// produced E1 has a bug worth hearing about.

export const LEVEL_ORDER: readonly EvidenceLevel[] = ['E0', 'E1', 'E2', 'E3', 'E4'];

export function rankOf(level: EvidenceLevel): number {
  return LEVEL_ORDER.indexOf(level);
}

export function atLeast(actual: EvidenceLevel, required: EvidenceLevel): boolean {
  return rankOf(actual) >= rankOf(required);
}

export const LEVEL_MEANING: Record<EvidenceLevel, string> = {
  E0: 'Claim. No supporting artifact. Cannot satisfy an acceptance criterion.',
  E1: 'Manual observation. Useful in development, insufficient for a critical security gate.',
  E2: 'Automated test result identifying the exact source revision.',
  E3: 'System-generated verified evidence. The default minimum for a significant release gate.',
  E4: 'Independently verified release evidence. Required for critical staging and canary gates.',
};

// Executors whose output is generated by a system rather than narrated by a
// person. An agent is deliberately not in this set: an agent reporting its own
// success is exactly the failure mode section 33 is written against.
const SYSTEM_EXECUTORS = new Set(['ci', 'database', 'runtime']);

export type LevelInput = Pick<
  EvidenceRecord,
  'code' | 'executorType' | 'evidenceLocation' | 'evidenceHash' | 'reproductionCommand' | 'status'
>;

export type LevelAssessment = {
  achieved: EvidenceLevel;
  reasons: string[];
};

export function assessLevel(
  input: LevelInput,
  context: {
    verifications?: readonly EvidenceVerification[];
    unresolvedBlockers?: number;
  } = {},
): LevelAssessment {
  const reasons: string[] = [];
  const hasArtifact = Boolean(input.evidenceLocation.trim()) && Boolean(input.evidenceHash.trim());

  if (!hasArtifact) {
    reasons.push('no artifact was stored, so this is a statement rather than evidence');
    return { achieved: 'E0', reasons };
  }

  const identifiesCommit = input.code.commitSha.trim().length >= 7;
  if (!identifiesCommit) {
    reasons.push('the artifact does not identify the exact source revision');
    return { achieved: 'E1', reasons };
  }

  if (!SYSTEM_EXECUTORS.has(input.executorType)) {
    reasons.push(`${input.executorType} execution is an observation, not a system-generated artifact`);
    return { achieved: 'E1', reasons };
  }

  if (!input.reproductionCommand?.trim()) {
    reasons.push('no reproduction command, so a third party cannot re-run it');
    return { achieved: 'E2', reasons };
  }

  const independent = (context.verifications ?? []).filter((v) => v.verdict === 'satisfies');
  if (independent.length === 0) {
    reasons.push('no independent reviewer has confirmed the artifact answers the criterion');
    return { achieved: 'E3', reasons };
  }

  const blockers = context.unresolvedBlockers ?? 0;
  if (blockers > 0) {
    reasons.push(`${blockers} unresolved blocker(s) stand between this artifact and a release claim`);
    return { achieved: 'E3', reasons };
  }

  // A verification is only worth anything if it looked at the same code.
  const sameCommit = independent.some((v) => v.checkedCommitSha === input.code.commitSha);
  if (!sameCommit) {
    reasons.push('the independent review was performed against a different commit');
    return { achieved: 'E3', reasons };
  }

  reasons.push('exact commit, reproducible test, system artifact, independent reviewer, no unresolved blocker');
  return { achieved: 'E4', reasons };
}

// A record is stored at the level it earned. Claiming more is refused so that
// the ladder cannot be climbed by assertion.
export function assertLevelClaim(claimed: EvidenceLevel, assessment: LevelAssessment) {
  if (rankOf(claimed) > rankOf(assessment.achieved)) {
    refuse(
      'evidence_level_overclaimed',
      `claimed ${claimed} but the artifact reaches ${assessment.achieved}: ${assessment.reasons.join('; ')}`,
    );
  }
}
