import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { verifyAlignmentKeyRotation, type AlignmentKeyRotationContext, type SignedAlignmentKeyRotation } from './alignment-key-rotation';
import type { EcosystemTarget } from './ecosystem-alignment';

type TrustSnapshot={tenantId:string;universeId:string;version:number;targets:Partial<Record<EcosystemTarget,{keyId:string;publicKeyPem:string;revision:string;retired:{keyId:string;publicKeyPem:string;revision:string}[]}>>;lastMutationDigest:string|null};
const SAFE=/^[A-Za-z0-9_-]{1,80}$/;

export class LocalAlignmentTrustStore {
  private readonly path:string;private snapshot:TrustSnapshot;
  constructor(input:{rootDirectory:string;tenantId:string;universeId:string}){if(!SAFE.test(input.tenantId)||!SAFE.test(input.universeId))throw new Error('invalid_scope');const root=resolve(input.rootDirectory);if(root===resolve('/')||root===resolve(process.cwd()))throw new Error('unsafe_storage_root');const dir=join(root,input.tenantId,input.universeId);mkdirSync(dir,{recursive:true,mode:0o700});this.path=join(dir,'alignment-trust.json');try{this.snapshot=JSON.parse(readFileSync(this.path,'utf8')) as TrustSnapshot;if(this.snapshot.tenantId!==input.tenantId||this.snapshot.universeId!==input.universeId)throw new Error('trust_store_scope_mismatch')}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;this.snapshot={tenantId:input.tenantId,universeId:input.universeId,version:0,targets:{},lastMutationDigest:null}}}
  initialize(input:{target:EcosystemTarget;keyId:string;publicKeyPem:string;revision:string}){if(this.snapshot.targets[input.target])throw new Error('target_already_initialized');this.snapshot.targets[input.target]={...input,retired:[]};this.snapshot.version+=1;this.persist();return this.status(input.target)}
  applyRotation(input:{expectedVersion:number;context:AlignmentKeyRotationContext;receipt:SignedAlignmentKeyRotation}){if(input.expectedVersion!==this.snapshot.version)throw new Error('stale_trust_store_version');const current=this.snapshot.targets[input.context.target];if(!current||current.keyId!==input.context.previousKeyId||current.publicKeyPem!==input.context.previousPublicKeyPem||current.revision!==input.context.expectedSourceRevision)throw new Error('current_trust_mismatch');const verified=verifyAlignmentKeyRotation(input.context,input.receipt);if(!verified.approved)throw new Error(`rotation_not_approved:${verified.reason}`);const previous={keyId:current.keyId,publicKeyPem:current.publicKeyPem,revision:current.revision};this.snapshot.targets[input.context.target]={keyId:input.context.newKeyId,publicKeyPem:input.context.newPublicKeyPem,revision:input.receipt.payload.sourceRevision,retired:[...current.retired,previous]};this.snapshot.version+=1;this.snapshot.lastMutationDigest=createHash('sha256').update(JSON.stringify(input.receipt)).digest('hex');this.persist();return{...this.status(input.context.target),applied:true as const,rollbackAvailable:true as const,rollbackExecuted:false as const,productionProviderActivated:false as const,partnershipClaimed:false as const}}
  status(target:EcosystemTarget){const current=this.snapshot.targets[target];return{tenantId:this.snapshot.tenantId,universeId:this.snapshot.universeId,version:this.snapshot.version,target,configured:Boolean(current),keyId:current?.keyId??null,revision:current?.revision??null,retiredKeyCount:current?.retired.length??0,lastMutationDigest:this.snapshot.lastMutationDigest,productionLive:false as const,grantsAuthority:false as const}}
  private persist(){const temp=`${this.path}.next`;writeFileSync(temp,JSON.stringify(this.snapshot),{encoding:'utf8',mode:0o600});renameSync(temp,this.path)}
}
