import { createHash, createPublicKey, verify } from 'node:crypto';
import type { AlignmentReplayStore } from './alignment-receipt';
import type { EcosystemTarget } from './ecosystem-alignment';

export type AlignmentKeyRotationPayload={tenantId:string;universeId:string;target:EcosystemTarget;issuerId:string;previousKeyId:string;newKeyId:string;newPublicKeyDigest:string;nonce:string;issuedAt:string;expiresAt:string;sourceRevision:string;humanApprovalRef:string};
export type SignedAlignmentKeyRotation={payload:AlignmentKeyRotationPayload;signature:string};
export type AlignmentKeyRotationContext={tenantId:string;universeId:string;target:EcosystemTarget;issuerId:string;previousKeyId:string;previousPublicKeyPem:string;newKeyId:string;newPublicKeyPem:string;expectedSourceRevision:string;expectedHumanApprovalRef:string;now:Date;maxClockSkewMs:number;revokedKeyIds:ReadonlySet<string>;replayStore:AlignmentReplayStore;mode:'TEST'|'OPERATIONAL'};
const fields:readonly(keyof AlignmentKeyRotationPayload)[]=['tenantId','universeId','target','issuerId','previousKeyId','newKeyId','newPublicKeyDigest','nonce','issuedAt','expiresAt','sourceRevision','humanApprovalRef'];const SAFE=/^[A-Za-z0-9_-]{1,80}$/;
export function serializeAlignmentKeyRotation(p:AlignmentKeyRotationPayload){return JSON.stringify(Object.fromEntries(fields.map((key)=>[key,p[key]])))}
export function alignmentPublicKeyDigest(pem:string){const key=createPublicKey(pem);if(key.asymmetricKeyType!=='ed25519')throw new Error('ed25519_public_key_required');return createHash('sha256').update(key.export({type:'spki',format:'der'})).digest('hex')}
function denied(reason:string){return{approved:false as const,state:'DENIED' as const,reason,trustStoreUpdated:false as const,oldKeyRevoked:false as const,productionWritePerformed:false as const,partnershipClaimed:false as const}}
export function verifyAlignmentKeyRotation(c:AlignmentKeyRotationContext,r:SignedAlignmentKeyRotation){const p=r.payload,serialized=serializeAlignmentKeyRotation(p);if(Buffer.byteLength(serialized)+Buffer.byteLength(r.signature)>8192)return denied('receipt_too_large');if(p.tenantId!==c.tenantId||p.universeId!==c.universeId||p.target!==c.target||p.issuerId!==c.issuerId)return denied('scope_mismatch');if(p.previousKeyId!==c.previousKeyId||p.newKeyId!==c.newKeyId||p.previousKeyId===p.newKeyId)return denied('key_transition_mismatch');if(!SAFE.test(p.nonce)||!SAFE.test(p.humanApprovalRef))return denied('invalid_nonce_or_approval');if(c.revokedKeyIds.has(p.previousKeyId))return denied('previous_key_revoked');if(c.revokedKeyIds.has(p.newKeyId))return denied('new_key_revoked');if(p.sourceRevision!==c.expectedSourceRevision||p.humanApprovalRef!==c.expectedHumanApprovalRef)return denied('configured_evidence_mismatch');try{if(/PRIVATE KEY/.test(c.previousPublicKeyPem)||/PRIVATE KEY/.test(c.newPublicKeyPem))return denied('public_ed25519_keys_required');if(alignmentPublicKeyDigest(c.newPublicKeyPem)!==p.newPublicKeyDigest)return denied('new_key_digest_mismatch');const old=createPublicKey(c.previousPublicKeyPem);if(old.asymmetricKeyType!=='ed25519')return denied('public_ed25519_keys_required');const signature=Buffer.from(r.signature,'base64');if(signature.length!==64||signature.toString('base64')!==r.signature)return denied('invalid_signature_encoding');if(!verify(null,Buffer.from(serialized),old,signature))return denied('invalid_signature')}catch{return denied('invalid_signature')}const issued=Date.parse(p.issuedAt),expires=Date.parse(p.expiresAt),now=c.now.getTime();if(!Number.isFinite(issued)||!Number.isFinite(expires)||expires<=issued)return denied('invalid_time_window');if(issued>now+c.maxClockSkewMs)return denied('receipt_from_future');if(expires<now)return denied('receipt_expired');if(c.mode==='OPERATIONAL'&&c.replayStore.durability!=='DURABLE')return denied('durable_replay_store_required');try{if(!c.replayStore.reserve([p.tenantId,p.universeId,p.target,p.previousKeyId,p.newKeyId,p.nonce].join(':')))return denied('receipt_replayed')}catch{return denied('replay_store_unavailable')}return{approved:true as const,state:'APPROVED_FOR_CONFIGURED_TRUST_UPDATE' as const,reason:null,trustStoreUpdated:false as const,oldKeyRevoked:false as const,productionWritePerformed:false as const,partnershipClaimed:false as const}}
