import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { verifyAlignmentKeyRotation, type AlignmentKeyRotationContext, type SignedAlignmentKeyRotation } from './alignment-key-rotation';
import { verifyAlignmentKeyRollback, type AlignmentKeyRollbackContext, type SignedAlignmentKeyRollback } from './alignment-key-rollback';
import type { EcosystemTarget } from './ecosystem-alignment';

type TrustMutation={sequence:number;kind:'INITIALIZE'|'ROTATE'|'ROLLBACK';target:EcosystemTarget;fromKeyId:string|null;toKeyId:string;storeVersion:number;evidenceDigest:string;previousHash:string;eventHash:string};
type TrustSnapshot={tenantId:string;universeId:string;version:number;targets:Partial<Record<EcosystemTarget,{keyId:string;publicKeyPem:string;revision:string;retired:{keyId:string;publicKeyPem:string;revision:string}[]}>>;lastMutationDigest:string|null;mutations?:TrustMutation[]};
const SAFE=/^[A-Za-z0-9_-]{1,80}$/;

export class LocalAlignmentTrustStore {
  private readonly path:string;private snapshot:TrustSnapshot;
  constructor(input:{rootDirectory:string;tenantId:string;universeId:string}){if(!SAFE.test(input.tenantId)||!SAFE.test(input.universeId))throw new Error('invalid_scope');const root=resolve(input.rootDirectory);if(root===resolve('/')||root===resolve(process.cwd()))throw new Error('unsafe_storage_root');const dir=join(root,input.tenantId,input.universeId);mkdirSync(dir,{recursive:true,mode:0o700});this.path=join(dir,'alignment-trust.json');try{this.snapshot=JSON.parse(readFileSync(this.path,'utf8')) as TrustSnapshot;if(this.snapshot.tenantId!==input.tenantId||this.snapshot.universeId!==input.universeId)throw new Error('trust_store_scope_mismatch');this.verifyAudit()}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;this.snapshot={tenantId:input.tenantId,universeId:input.universeId,version:0,targets:{},lastMutationDigest:null,mutations:[]}}}
  initialize(input:{target:EcosystemTarget;keyId:string;publicKeyPem:string;revision:string}){if(this.snapshot.targets[input.target])throw new Error('target_already_initialized');this.snapshot.targets[input.target]={...input,retired:[]};this.snapshot.version+=1;this.recordMutation('INITIALIZE',input.target,null,input.keyId,createHash('sha256').update(input.publicKeyPem).digest('hex'));this.persist();return this.status(input.target)}
  applyRotation(input:{expectedVersion:number;context:AlignmentKeyRotationContext;receipt:SignedAlignmentKeyRotation}){if(input.expectedVersion!==this.snapshot.version)throw new Error('stale_trust_store_version');const current=this.snapshot.targets[input.context.target];if(!current||current.keyId!==input.context.previousKeyId||current.publicKeyPem!==input.context.previousPublicKeyPem||current.revision!==input.context.expectedSourceRevision)throw new Error('current_trust_mismatch');const verified=verifyAlignmentKeyRotation(input.context,input.receipt);if(!verified.approved)throw new Error(`rotation_not_approved:${verified.reason}`);const previous={keyId:current.keyId,publicKeyPem:current.publicKeyPem,revision:current.revision};this.snapshot.targets[input.context.target]={keyId:input.context.newKeyId,publicKeyPem:input.context.newPublicKeyPem,revision:input.receipt.payload.sourceRevision,retired:[...current.retired,previous]};this.snapshot.version+=1;this.recordMutation('ROTATE',input.context.target,previous.keyId,input.context.newKeyId,createHash('sha256').update(JSON.stringify(input.receipt)).digest('hex'));this.persist();return{...this.status(input.context.target),applied:true as const,rollbackAvailable:true as const,rollbackExecuted:false as const,productionProviderActivated:false as const,partnershipClaimed:false as const}}
  applyRollback(input:{expectedVersion:number;context:AlignmentKeyRollbackContext;receipt:SignedAlignmentKeyRollback}){if(input.expectedVersion!==this.snapshot.version||input.context.expectedStoreVersion!==this.snapshot.version)throw new Error('stale_trust_store_version');const current=this.snapshot.targets[input.context.target],restore=current?.retired.find((key)=>key.keyId===input.context.restoreKeyId);if(!current||current.keyId!==input.context.currentKeyId||current.revision!==input.context.currentRevision||!restore||restore.revision!==input.context.restoreRevision)throw new Error('rollback_trust_mismatch');const verified=verifyAlignmentKeyRollback(input.context,input.receipt);if(!verified.approved)throw new Error(`rollback_not_approved:${verified.reason}`);const retired=current.retired.filter((key)=>key.keyId!==restore.keyId);retired.push({keyId:current.keyId,publicKeyPem:current.publicKeyPem,revision:current.revision});this.snapshot.targets[input.context.target]={keyId:restore.keyId,publicKeyPem:restore.publicKeyPem,revision:restore.revision,retired};this.snapshot.version+=1;this.recordMutation('ROLLBACK',input.context.target,current.keyId,restore.keyId,createHash('sha256').update(JSON.stringify(input.receipt)).digest('hex'));this.persist();return{...this.status(input.context.target),applied:true as const,rollbackExecuted:true as const,localReferenceOnly:true as const,productionProviderActivated:false as const,partnershipClaimed:false as const}}
  status(target:EcosystemTarget){const current=this.snapshot.targets[target];return{tenantId:this.snapshot.tenantId,universeId:this.snapshot.universeId,version:this.snapshot.version,target,configured:Boolean(current),keyId:current?.keyId??null,revision:current?.revision??null,retiredKeyCount:current?.retired.length??0,lastMutationDigest:this.snapshot.lastMutationDigest,auditEventCount:this.snapshot.mutations?.length??0,auditComplete:Boolean(this.snapshot.mutations),productionLive:false as const,grantsAuthority:false as const}}
  auditTrail(){return (this.snapshot.mutations??[]).map((event)=>({...event,publicKeysExposed:false as const,productionWritePerformed:false as const}))}
  checkpointState(){return{tenantId:this.snapshot.tenantId,universeId:this.snapshot.universeId,storeVersion:this.snapshot.version,eventCount:this.snapshot.mutations?.length??0,chainHead:this.snapshot.mutations?.at(-1)?.eventHash??null,auditComplete:Boolean(this.snapshot.mutations),containsKeyMaterial:false as const,productionLive:false as const}}
  private recordMutation(kind:TrustMutation['kind'],target:EcosystemTarget,fromKeyId:string|null,toKeyId:string,evidenceDigest:string){const events=this.snapshot.mutations??[],unsigned={sequence:events.length+1,kind,target,fromKeyId,toKeyId,storeVersion:this.snapshot.version,evidenceDigest,previousHash:events.at(-1)?.eventHash??'GENESIS'},eventHash=createHash('sha256').update(JSON.stringify(unsigned)).digest('hex');this.snapshot.mutations=[...events,{...unsigned,eventHash}];this.snapshot.lastMutationDigest=eventHash}
  private verifyAudit(){if(!this.snapshot.mutations)return;let previous='GENESIS';for(const event of this.snapshot.mutations){const{eventHash,...unsigned}=event;if(event.previousHash!==previous||event.sequence<1||createHash('sha256').update(JSON.stringify(unsigned)).digest('hex')!==eventHash)throw new Error('trust_mutation_chain_invalid');previous=eventHash}if((this.snapshot.mutations.at(-1)?.eventHash??null)!==this.snapshot.lastMutationDigest)throw new Error('trust_mutation_chain_invalid')}
  private persist(){const temp=`${this.path}.next`;writeFileSync(temp,JSON.stringify(this.snapshot),{encoding:'utf8',mode:0o600});renameSync(temp,this.path)}
}
