import { createPublicKey, verify } from 'node:crypto';
import type { AlignmentReplayStore } from './alignment-receipt';

export type AlignmentAuditCheckpointPayload={tenantId:string;universeId:string;storeVersion:number;eventCount:number;chainHead:string;privacyAuthorityId:string;privacyKeyId:string;securityAuthorityId:string;securityKeyId:string;nonce:string;issuedAt:string;expiresAt:string;sourceRevision:string;humanApprovalRef:string};
export type SignedAlignmentAuditCheckpoint={payload:AlignmentAuditCheckpointPayload;privacySignature:string;securitySignature:string};
export type AlignmentAuditCheckpointContext={tenantId:string;universeId:string;storeVersion:number;eventCount:number;chainHead:string;privacyAuthorityId:string;privacyKeyId:string;privacyPublicKeyPem:string;securityAuthorityId:string;securityKeyId:string;securityPublicKeyPem:string;expectedSourceRevision:string;expectedHumanApprovalRef:string;now:Date;maxClockSkewMs:number;revokedKeyIds:ReadonlySet<string>;replayStore:AlignmentReplayStore;mode:'TEST'|'OPERATIONAL'};
const fields:readonly(keyof AlignmentAuditCheckpointPayload)[]=['tenantId','universeId','storeVersion','eventCount','chainHead','privacyAuthorityId','privacyKeyId','securityAuthorityId','securityKeyId','nonce','issuedAt','expiresAt','sourceRevision','humanApprovalRef'],SAFE=/^[A-Za-z0-9_-]{1,80}$/,DIGEST=/^[a-f0-9]{64}$/;
export function serializeAlignmentAuditCheckpoint(p:AlignmentAuditCheckpointPayload){return JSON.stringify(Object.fromEntries(fields.map((key)=>[key,p[key]])))}
function denied(reason:string){return{verified:false as const,state:'DENIED' as const,reason,checkpointPersisted:false as const,trustStoreModified:false as const,productionWritePerformed:false as const,providerActivated:false as const}}
function signatureValid(serialized:string,signature:string,pem:string){if(/PRIVATE KEY/.test(pem))return false;const key=createPublicKey(pem);if(key.asymmetricKeyType!=='ed25519')return false;const bytes=Buffer.from(signature,'base64');return bytes.length===64&&bytes.toString('base64')===signature&&verify(null,Buffer.from(serialized),key,bytes)}
export function verifyAlignmentAuditCheckpoint(c:AlignmentAuditCheckpointContext,r:SignedAlignmentAuditCheckpoint){const p=r.payload,serialized=serializeAlignmentAuditCheckpoint(p);if(Buffer.byteLength(serialized)+Buffer.byteLength(r.privacySignature)+Buffer.byteLength(r.securitySignature)>12288)return denied('checkpoint_too_large');if(p.tenantId!==c.tenantId||p.universeId!==c.universeId)return denied('scope_mismatch');if(p.storeVersion!==c.storeVersion||p.eventCount!==c.eventCount||p.chainHead!==c.chainHead||p.eventCount<1||!DIGEST.test(p.chainHead))return denied('audit_state_mismatch');if(p.privacyAuthorityId!==c.privacyAuthorityId||p.privacyKeyId!==c.privacyKeyId||p.securityAuthorityId!==c.securityAuthorityId||p.securityKeyId!==c.securityKeyId)return denied('authority_mismatch');if(p.privacyAuthorityId===p.securityAuthorityId||p.privacyKeyId===p.securityKeyId)return denied('independent_authorities_required');if(!SAFE.test(p.nonce)||!SAFE.test(p.humanApprovalRef)||p.sourceRevision!==c.expectedSourceRevision||p.humanApprovalRef!==c.expectedHumanApprovalRef)return denied('configured_evidence_mismatch');if(c.revokedKeyIds.has(p.privacyKeyId)||c.revokedKeyIds.has(p.securityKeyId))return denied('revoked_key');try{if(!signatureValid(serialized,r.privacySignature,c.privacyPublicKeyPem)||!signatureValid(serialized,r.securitySignature,c.securityPublicKeyPem))return denied('invalid_signature')}catch{return denied('invalid_signature')}const issued=Date.parse(p.issuedAt),expires=Date.parse(p.expiresAt),now=c.now.getTime();if(!Number.isFinite(issued)||!Number.isFinite(expires)||expires<=issued)return denied('invalid_time_window');if(issued>now+c.maxClockSkewMs)return denied('checkpoint_from_future');if(expires<now)return denied('checkpoint_expired');if(c.mode==='OPERATIONAL'&&c.replayStore.durability!=='DURABLE')return denied('durable_replay_store_required');try{if(!c.replayStore.reserve([p.tenantId,p.universeId,p.storeVersion,p.chainHead,p.nonce].join(':')))return denied('checkpoint_replayed')}catch{return denied('replay_store_unavailable')}return{verified:true as const,state:'VERIFIED_EXTERNAL_AUDIT_CHECKPOINT' as const,reason:null,checkpointPersisted:false as const,trustStoreModified:false as const,productionWritePerformed:false as const,providerActivated:false as const}}
