import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { verifyAlignmentAuditCheckpoint, type AlignmentAuditCheckpointContext, type SignedAlignmentAuditCheckpoint } from './alignment-audit-checkpoint';

type StoredCheckpoint={storeVersion:number;eventCount:number;chainHead:string;sourceRevision:string;humanApprovalRef:string;receiptDigest:string;acceptedAt:string};
type CheckpointSnapshot={tenantId:string;universeId:string;version:number;latest:StoredCheckpoint|null;snapshotDigest:string};
const SAFE=/^[A-Za-z0-9_-]{1,80}$/;
function digest(snapshot:Omit<CheckpointSnapshot,'snapshotDigest'>){return createHash('sha256').update(JSON.stringify(snapshot)).digest('hex')}

export class LocalAlignmentCheckpointStore{
  private readonly path:string;private snapshot:CheckpointSnapshot;
  constructor(input:{rootDirectory:string;tenantId:string;universeId:string}){if(!SAFE.test(input.tenantId)||!SAFE.test(input.universeId))throw new Error('invalid_scope');const root=resolve(input.rootDirectory);if(root===resolve('/')||root===resolve(process.cwd()))throw new Error('unsafe_storage_root');const directory=join(root,input.tenantId,input.universeId);mkdirSync(directory,{recursive:true,mode:0o700});this.path=join(directory,'alignment-checkpoints.json');try{this.snapshot=JSON.parse(readFileSync(this.path,'utf8')) as CheckpointSnapshot;const{snapshotDigest,...unsigned}=this.snapshot;if(this.snapshot.tenantId!==input.tenantId||this.snapshot.universeId!==input.universeId)throw new Error('checkpoint_store_scope_mismatch');if(digest(unsigned)!==snapshotDigest)throw new Error('checkpoint_snapshot_invalid')}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;const unsigned={tenantId:input.tenantId,universeId:input.universeId,version:0,latest:null};this.snapshot={...unsigned,snapshotDigest:digest(unsigned)}}}
  accept(input:{expectedVersion:number;context:AlignmentAuditCheckpointContext;receipt:SignedAlignmentAuditCheckpoint;now?:Date}){if(input.expectedVersion!==this.snapshot.version)throw new Error('stale_checkpoint_store_version');const previous=this.snapshot.latest,payload=input.receipt.payload;if(previous&&(payload.storeVersion<=previous.storeVersion||payload.eventCount<=previous.eventCount))throw new Error('checkpoint_regression');const verified=verifyAlignmentAuditCheckpoint(input.context,input.receipt);if(!verified.verified)throw new Error(`checkpoint_not_verified:${verified.reason}`);const latest:StoredCheckpoint={storeVersion:payload.storeVersion,eventCount:payload.eventCount,chainHead:payload.chainHead,sourceRevision:payload.sourceRevision,humanApprovalRef:payload.humanApprovalRef,receiptDigest:createHash('sha256').update(JSON.stringify(input.receipt)).digest('hex'),acceptedAt:(input.now??input.context.now).toISOString()},unsigned={tenantId:this.snapshot.tenantId,universeId:this.snapshot.universeId,version:this.snapshot.version+1,latest},next={...unsigned,snapshotDigest:digest(unsigned)};this.persist(next);this.snapshot=next;return{...this.status(),accepted:true as const,trustStoreModified:false as const,productionWritePerformed:false as const,providerActivated:false as const}}
  status(){return{tenantId:this.snapshot.tenantId,universeId:this.snapshot.universeId,version:this.snapshot.version,configured:Boolean(this.snapshot.latest),storeVersion:this.snapshot.latest?.storeVersion??null,eventCount:this.snapshot.latest?.eventCount??0,chainHead:this.snapshot.latest?.chainHead??null,acceptedAt:this.snapshot.latest?.acceptedAt??null,signaturesExposed:false as const,trustStoreModified:false as const,productionLive:false as const}}
  private persist(snapshot:CheckpointSnapshot){const temp=`${this.path}.next`;writeFileSync(temp,JSON.stringify(snapshot),{encoding:'utf8',mode:0o600});renameSync(temp,this.path)}
}
