import { createPublicKey, verify } from 'node:crypto';
import type { AlignmentReplayStore } from './alignment-receipt';
import type { EcosystemTarget } from './ecosystem-alignment';

export type AlignmentKeyRollbackPayload={tenantId:string;universeId:string;target:EcosystemTarget;currentKeyId:string;restoreKeyId:string;expectedStoreVersion:number;currentRevision:string;restoreRevision:string;privacyAuthorityId:string;privacyKeyId:string;securityAuthorityId:string;securityKeyId:string;nonce:string;issuedAt:string;expiresAt:string;sourceRevision:string;humanApprovalRef:string};
export type SignedAlignmentKeyRollback={payload:AlignmentKeyRollbackPayload;privacySignature:string;securitySignature:string};
export type AlignmentKeyRollbackContext={tenantId:string;universeId:string;target:EcosystemTarget;currentKeyId:string;restoreKeyId:string;expectedStoreVersion:number;currentRevision:string;restoreRevision:string;privacyAuthorityId:string;privacyKeyId:string;privacyPublicKeyPem:string;securityAuthorityId:string;securityKeyId:string;securityPublicKeyPem:string;expectedSourceRevision:string;expectedHumanApprovalRef:string;now:Date;maxClockSkewMs:number;revokedKeyIds:ReadonlySet<string>;replayStore:AlignmentReplayStore;mode:'TEST'|'OPERATIONAL'};
const fields:readonly(keyof AlignmentKeyRollbackPayload)[]=['tenantId','universeId','target','currentKeyId','restoreKeyId','expectedStoreVersion','currentRevision','restoreRevision','privacyAuthorityId','privacyKeyId','securityAuthorityId','securityKeyId','nonce','issuedAt','expiresAt','sourceRevision','humanApprovalRef'];
const SAFE=/^[A-Za-z0-9_-]{1,80}$/;
export function serializeAlignmentKeyRollback(p:AlignmentKeyRollbackPayload){return JSON.stringify(Object.fromEntries(fields.map((key)=>[key,p[key]])))}
function denied(reason:string){return{approved:false as const,state:'DENIED' as const,reason,trustStoreUpdated:false as const,rollbackExecuted:false as const,productionWritePerformed:false as const,providerActivated:false as const}}
function validSignature(serialized:string,signature:string,pem:string){if(/PRIVATE KEY/.test(pem))return false;const key=createPublicKey(pem);if(key.asymmetricKeyType!=='ed25519')return false;const bytes=Buffer.from(signature,'base64');return bytes.length===64&&bytes.toString('base64')===signature&&verify(null,Buffer.from(serialized),key,bytes)}
export function verifyAlignmentKeyRollback(c:AlignmentKeyRollbackContext,r:SignedAlignmentKeyRollback){const p=r.payload,serialized=serializeAlignmentKeyRollback(p);if(Buffer.byteLength(serialized)+Buffer.byteLength(r.privacySignature)+Buffer.byteLength(r.securitySignature)>12288)return denied('receipt_too_large');if(p.tenantId!==c.tenantId||p.universeId!==c.universeId||p.target!==c.target)return denied('scope_mismatch');if(p.currentKeyId!==c.currentKeyId||p.restoreKeyId!==c.restoreKeyId||p.currentKeyId===p.restoreKeyId||p.expectedStoreVersion!==c.expectedStoreVersion||p.currentRevision!==c.currentRevision||p.restoreRevision!==c.restoreRevision)return denied('rollback_state_mismatch');if(p.privacyAuthorityId!==c.privacyAuthorityId||p.privacyKeyId!==c.privacyKeyId||p.securityAuthorityId!==c.securityAuthorityId||p.securityKeyId!==c.securityKeyId)return denied('authority_mismatch');if(p.privacyAuthorityId===p.securityAuthorityId||p.privacyKeyId===p.securityKeyId)return denied('independent_authorities_required');if(!SAFE.test(p.nonce)||!SAFE.test(p.humanApprovalRef))return denied('invalid_nonce_or_approval');if(p.sourceRevision!==c.expectedSourceRevision||p.humanApprovalRef!==c.expectedHumanApprovalRef)return denied('configured_evidence_mismatch');if(c.revokedKeyIds.has(p.currentKeyId)||c.revokedKeyIds.has(p.restoreKeyId)||c.revokedKeyIds.has(p.privacyKeyId)||c.revokedKeyIds.has(p.securityKeyId))return denied('revoked_key');try{if(!validSignature(serialized,r.privacySignature,c.privacyPublicKeyPem)||!validSignature(serialized,r.securitySignature,c.securityPublicKeyPem))return denied('invalid_signature')}catch{return denied('invalid_signature')}const issued=Date.parse(p.issuedAt),expires=Date.parse(p.expiresAt),now=c.now.getTime();if(!Number.isFinite(issued)||!Number.isFinite(expires)||expires<=issued)return denied('invalid_time_window');if(issued>now+c.maxClockSkewMs)return denied('receipt_from_future');if(expires<now)return denied('receipt_expired');if(c.mode==='OPERATIONAL'&&c.replayStore.durability!=='DURABLE')return denied('durable_replay_store_required');try{if(!c.replayStore.reserve([p.tenantId,p.universeId,p.target,p.currentKeyId,p.restoreKeyId,p.expectedStoreVersion,p.nonce].join(':')))return denied('receipt_replayed')}catch{return denied('replay_store_unavailable')}return{approved:true as const,state:'APPROVED_FOR_ATOMIC_LOCAL_ROLLBACK' as const,reason:null,trustStoreUpdated:false as const,rollbackExecuted:false as const,productionWritePerformed:false as const,providerActivated:false as const}}
