/**
 * 12D-113: KNOWN alignment debt for *_GUARDRAILS objects that predate the governed
 * alignment invariants. This ledger was GENERATED by the 12D-113 audit on the tree at
 * branch claude/12d-99-supervised-local-worker (2026-09-13) — every entry is a real,
 * mechanically-verified violation (missing Object.freeze and/or humanDecision REQUIRED).
 *
 * 12D-117 paid down the ENTIRE ledger: every listed guardrails object was frozen and
 * given humanDecision: 'REQUIRED' in the same change, so the ledger is now empty.
 *
 * The ledger may only SHRINK: the audit fails if (a) a violation exists that is not in
 * this ledger, or (b) an entry here becomes compliant without being removed from the
 * ledger. New unfrozen guardrails objects are new debt and must not be added here.
 */
export type GuardrailsDebtFacet = 'freeze' | 'humanDecision';
export interface KnownGuardrailsDebtEntry { readonly file: string; readonly object: string; readonly missing: readonly GuardrailsDebtFacet[]; }
export const KNOWN_GUARDRAILS_DEBT: readonly KnownGuardrailsDebtEntry[] = Object.freeze([
] as KnownGuardrailsDebtEntry[]);