export * from './types';
export * from './orchestrator';
export * from './grok-bridge';
export * from './work-queue';
export * from './recovery-journal';
export * from './openai-local';
export * from './local-store';
export * from './hardware-receipts';
export * from './data-mining';
export * from './defensive-security';
export * from './worker-daemon';
export * from './adaptive-agent-factory';
export * from './peer-learning-mesh';
export * from './storage-compiler';
export * from './parallel-scenario-compiler';
export * from './control-tower';
export * from './public-data-ingest';
export * from './neural-highway';
export * from './model-council';
export * from './mission-scheduler';
export * from './xiv-genome';
export * from './virtual-family';
export * from './offline-plugin-runtime';
export * from './ollama-toolchain';
export * from './model-discovery';
export * from './live-supervisor';
export * from './supervisor-status';
export * from './ollama-job-executor';
export * from './review-learning-council';
export * from './virtual-cloud-chip-sim';
export * from './consultant-academy';
export * from './historical-intelligence-registry';
export * from './experience-modes';
export * from './cross-os-runtime';
export * from './community-universe';
export * from './neuron-fabric';
export * from './team-operations';
export * from './database-growth-manifest';
export * from './blueprint-conformance';
export * from './monetization';
export * from './finance-council';
export * from './revenue-scenarios';
export * from './monetization-evidence';
export * from './cfo-ollama-revenue-lab';
export * from './revenue-lab-council';
export * from './training-evaluation-ledger';
export * from './revenue-lab-runner';
export * from './founder-twin';
export * from './virtual-coo';
export * from './confidential-vault';
export * from './leadership-genome';
export * from './document-governance-catalog';
export * from './ai-workforce-campus';
export * from './devops-team';
export * from './ai-hr';
export * from './study-curriculum';
export * from './agent-campus-meetings';
export * from './innovation-mental-gym';
export * from './agent-campus-runner';
export * from './multi-agent-meeting-bus';
export * from './executive-decision-packet';
export * from './ollama-meeting-runner';
export * from './executive-cabinet';
export * from './private-data-brain';
export * from './cloud-dna-package';
export * from './executive-cabinet-ollama-runner';
export * from './executive-cabinet-council';
export * from './company-brain-writeback';
export * from './executive-neuron-learning';
export * from './next-story-generator';
export * from './persistent-company-brain';
export * from './meeting-ingestion';
export * from './company-brain-search';
export * from './company-brain-disk-store';
export * from './meeting-folder-ingestion';
export * from './experience-backend';
export * from './experience-view-model';
export * from './local-experience-runner';
export * from './hybrid-agent-fleet';
export * from './hybrid-agent-router';
export * from './plugin-capability-gateway';
export * from './fleet-neural-learning';
export * from './mission-dispatcher';
export * from './full-stack-team';
export * from './lovable-capability-bridge';
export * from './parallel-scenario-lab';
export * from './ai-tool-api-registry';
export * from './agentic-search-engine';
export * from './civilization-knowledge-graph';
export * from './blue-brain-data-pipeline';
export * from './virtual-community-world';
export * from './live-tool-heartbeats';
export * from './agentic-search-worker';
export * from './device-pilot-enrollment';
export * from './device-pilot-policy';
export * from './local-learning-sandbox';
export * from './universal-device-compatibility';
export * from './device-capability-broker';
export * from './visual-intelligence-engine';
export * from './industry-visual-templates';
export * from './client-presentation-composer';
export * from './live-visual-dashboard';
export * from './story-visual-drilldown';
export * from './lovable-ux-sync-manifest';
export * from './client-visual-component-gateway';
export * from './offline-chart-data-service';
export * from './visual-interaction-contract';
export * from './xiv-experience-runtime';
export * from './experience-freshness';
export * from './ollama-story-explanation';
export * from './industry-ecosystem-graph';
export * from './case-study-team';
export * from './historical-knowledge-growth';
export * from './case-study-learning-pipeline';
export * from './case-study-ollama-lab';
export * from './industry-problem-simulator';
export * from './case-study-council';
export * from './elite-onboarding';
export * from './avatar-identity-twin';
export * from './defensive-security-swarm';
export * from './ai-tool-marketplace-bundles';
export * from './onboarding-experience-ui';
export * from './security-command-center-view';
export * from './avatar-universe-home';
export * from './privacy-consent-center';
export * from './live-onboarding-runtime';
export * from './avatar-brain-bootstrap';
export * from './permission-scoped-tool-loader';
export * from './avatar-universe-session';
export * from './offline-brain-health';
export * from './encrypted-memory-nervous-system';
export * from './simulation-scale-manifest';
export * from './neural-growth-scheduler';
export * from './historical-technology-archive';
export * from './agent-academy-learning-loop';
export * from './avatar-genome-registry';
export * from './historical-business-tech-archive';
export * from './devops-programming-library';
export * from './open-source-tool-collaboration-registry';
export * from './agent-media-study-room';
export * from './offline-learning-data-plane';
export * from './usage-analytics-ledger';
export * from './bookkeeping-ops';
export * from './team-task-meeting-orchestrator';
export * from './vendor-device-integration-registry';
export * from './local-agent-runtime-supervisor';
export * from './cpu-gpu-workload-scheduler';
export * from './private-local-api-gateway';
export * from './vault-audit-console';
export * from './lean-six-sigma-debug-loop';
export * from './xiv-homebase-recovery';
export * from './global-developer-mesh';
export * from './governed-tool-registry';
export * from './historical-archive-ingestion';
export * from './local-brain-growth-controller';
export * from './offline-online-tool-router';
export * from './partner-adapter-atlas';
export * from './sovereign-learning-api-studio-evidence-runtime';
export * from './runtime-convergence-validator';
export * from './offline-brain-agent-council';
export * from './offline-brain-execution-ledger';
export * from './local-model-collaboration-bus';
export * from './neural-pathway-growth-engine';
export * from './ollama-live-runtime-bridge';
export * from './agentic-brain-alignment-control-plane';

// 12D-93: Explicit origins for formerly ambiguous public names. Direct imports
// are unchanged; distinct sibling contracts stay available through named aliases.
export type { ExecutiveRole } from './executive-cabinet';
export type { ExecutiveRole as CabinetOllamaRole } from './executive-cabinet-ollama-runner';
export { buildExecutiveDecisionPacket } from './executive-decision-packet';
export type { ExecutiveDecisionPacket } from './executive-decision-packet';
export { buildExecutiveDecisionPacket as buildCabinetDecisionPacket } from './executive-cabinet-council';
export type { ExecutiveDecisionPacket as CabinetDecisionPacket } from './executive-cabinet-council';
export type { DataClass } from './private-data-brain';
export type { DataClass as ApiToolDataClass } from './ai-tool-api-registry';
export type { DataClass as GovernedToolDataClass } from './governed-tool-registry';
export { planAgenticSearch } from './agentic-search-engine';
export { planAgenticSearch as planAgenticSearchWorker } from './agentic-search-worker';
export type { OsFamily } from './cross-os-runtime';
export type { OsFamily as DeviceOsFamily } from './universal-device-compatibility';
export type { VisualEvidencePoint } from './visual-intelligence-engine';
export type { VisualEvidencePoint as DashboardEvidencePoint } from './live-visual-dashboard';
export type { VisualEvidencePoint as ComponentEvidencePoint } from './client-visual-component-gateway';
export type { EnrollmentReceipt } from './elite-onboarding';
export type { EnrollmentReceipt as LiveEnrollmentReceipt } from './live-onboarding-runtime';
export { HISTORICAL_ARCHIVE_GUARDRAILS } from './historical-technology-archive';
export { HISTORICAL_ARCHIVE_GUARDRAILS as HISTORICAL_BUSINESS_ARCHIVE_GUARDRAILS } from './historical-business-tech-archive';
export type { AgentMeeting } from './agent-campus-meetings';
export type { AgentMeeting as OperationsAgentMeeting } from './team-task-meeting-orchestrator';
export type { HistoricalArchiveRecord } from './historical-business-tech-archive';
export type { HistoricalArchiveRecord as IngestedHistoricalArchiveRecord } from './historical-archive-ingestion';
export type { PartnerState } from './industry-ecosystem-graph';
export type { PartnerState as AdapterPartnerState } from './partner-adapter-atlas';
export type { OllamaModelInfo } from './model-discovery';
export type { OllamaModelInfo as OllamaBridgeModelInfo } from './ollama-live-runtime-bridge';
export type { BrainSecurityClass } from './offline-brain-agent-council';
export type { BrainSecurityClass as AlignmentBrainSecurityClass } from './agentic-brain-alignment-control-plane';
// GitHub's inherited compiler and lab expose separate scenario contracts.
export type { ScenarioBranch } from './parallel-scenario-compiler';
export type { ScenarioBranch as LabScenarioBranch } from './parallel-scenario-lab';
